apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    generateName: testorg-testrepo-test13-
    labels:
        jobPRID: "113"
        jobRepositoryName: testorg-testrepo-test13
        pipeline/run-id: temp-home13-artifacts-123
spec:
    templates:
        - name: main
          steps:
            - - name: main-script
                template: main-script
            - - name: copy-script
                template: copy-script
        - name: main-script
          metadata: {}
          script:
            name: ascend
            image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1-910b-ubuntu22.04-py3.11
            command:
                - bash
            source: |
                #!/bin/sh
                echo "Building artifacts..."
                echo xxxx > test.txt
                echo yyyy > debug.log
                sleep 120
                echo "Build complete"

                cd ${WORKSPACE}
                cp -r --parents *.txt *.log /output/artifact/
            resources:
                limits:
                    memory: 8Gi
                requests:
                    cpu: "2"
                    memory: 8Gi
            volumeMounts:
                - name: output
                  mountPath: /output/artifact
            workingDir: /workspace
            env:
                - name: WORKSPACE
                  value: /workspace
                - name: MAX_JOBS
                  value: "2"
                - name: CMAKE_BUILD_PARALLEL_LEVEL
                  value: "2"
                - name: workspace
                  value: /workspace
                - name: BUILDNUMBER
                  value: "131415161"
                - name: JOB_ID
                  value: temp-job-home13
          nodeSelector:
            kubernetes.io/arch: amd64
        - name: copy-script
          script:
            name: ascend
            image: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/alpine:3.23.3
            command:
                - sh
            source: |
                #!/bin/sh
                echo "copying artifacts...."
                trap 'exit 0' TERM
                sleep infinity &
                wait $!
            resources:
                limits:
                    memory: 8Gi
                requests:
                    cpu: "2"
                    memory: 8Gi
            volumeMounts:
                - name: output
                  mountPath: /output/artifact
            workingDir: /workspace
            env:
                - name: WORKSPACE
                  value: /workspace
                - name: MAX_JOBS
                  value: "2"
                - name: CMAKE_BUILD_PARALLEL_LEVEL
                  value: "2"
          nodeSelector:
            kubernetes.io/arch: amd64
    entrypoint: main
    arguments: {}
    volumeClaimTemplates:
        - metadata:
            name: output
          spec:
            accessModes:
                - ReadWriteMany
            resources:
                requests:
                    storage: 1Gi
            storageClassName: sfsturbo-subpath-sc
    imagePullSecrets:
        - name: huawei-swr-image-pull-secret-model-gy
    schedulerName: volcano
    activeDeadlineSeconds: 14400
    securityContext:
        runAsUser: 0
