#!/bin/bash
export CP_runs_on="amd64-cpu-1-mem-1G"
export CP_docker_image="swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1-910b-ubuntu22.04-py3.11"
export CP_pipeline_run_id="test-pull-policy-123"
export CP_merge_id="42"
export CP_repo_url="https://github.com/testorg/testrepo-test36.git"
export JOB_ID="job-pull-policy"
export BUILDNUMBER="202406"
export WORKSPACE="/home/chenqi252/code/agentpk/opencode/codearts-workflow-image/go/cmd/converter/case/newtest/test36-image-pull-policy/artifacts"
export CP_timestamp="1036"
export CP_image_pull_policy="ifnotpresent"
