apiVersion: v1
kind: Pod
metadata:
  name: ${PVC_NAME}
  namespace: argo
  labels:
    pipeline/run-id: ${PIPELINE_RUN_ID}
spec:
  containers:
  - name: copy
    image: ${CP_cp_image}
    command: ["sleep", "1800"]
    volumeMounts:
    - name: artifact
      mountPath: /output/artifact
  volumes:
  - name: artifact
    persistentVolumeClaim:
      claimName: ${PVC_NAME}
  restartPolicy: Never