export CP_runs_on="arm64"
export CP_docker_image="swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1-910b-ubuntu22.04-py3.11"
export CP_pipeline_run_id="test-workspace-filter-123"
export CP_merge_id="20"
export CP_repo_url="https://github.com/testorg/testrepo-test7.git"
export WORKSPACE="/CP_workspace"
export workspace="/CP_workspace"
export JOB_ID="job-workspace"
export BUILDNUMBER="606606"
export CP_timestamp="1007"

export CP_image_proxy="swr.cn-southwest-2.myhuaweicloud.com"
