apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: argo-policy
  namespace: argo
spec:
  conflictResolution: Abort
  placement:
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided
  preemption: Never
  priority: 10
  resourceSelectors:
  - apiVersion: batch/v1
    kind: Job
    namespace: argo
  - apiVersion: batch.volcano.sh/v1alpha1
    kind: Job
    namespace: argo
  schedulerName: default-scheduler
