apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: member1-secret-policy
spec:
  conflictResolution: Abort
  priority: 100
  placement:
    clusterAffinity:
      clusterNames:
      - 001
  resourceSelectors:
  - apiVersion: v1
    kind: Secret
    labelSelector:
      matchLabels:
        dispatch/member1: 'true'
