export CP_runs_on="arm64"
export CP_docker_image="swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1-910b-ubuntu22.04-py3.11"
export CP_pipeline_run_id="test-empty-789"
export CP_merge_id="19"
export CP_repo_url="https://github.com/testorg/testrepo-test6.git"
export JOB_ID="job-empty"
export BUILDNUMBER="505505"
export gitcode_token=""
export CP_timestamp="1006"

export CP_image_proxy="swr.cn-southwest-2.myhuaweicloud.com"
