name: 'My code check'
description: 'A simple composite action example'
inputs:
  greeting:
    description: 'Greeting message'
    required: true
    default: 'Hello world'

runs:
  using: "composite"
  steps:
    - name: rucursivecall
      uses: ./../case/actions/recursivecall
