#!/bin/bash
export CP_runs_on="amd64-cpu-1-mem-1G"
export CP_docker_image="swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1-910b-ubuntu22.04-py3.11"
export CP_pipeline_run_id="test-5g-download-123"
export CP_merge_id="135"
export CP_repo_url="https://github.com/testorg/testrepo-test35.git"
export JOB_ID="job-5g-download"
export BUILDNUMBER="202406"
export WORKSPACE="/home/chenqi252/code/agentpk/opencode/codearts-workflow-image/go/cmd/converter/case/newtest/test35-ingress-bandwidth/artifacts"
export CP_timestamp="1035"
export CP_bandwidth="10M"
